[tool.black]
line-length = 120
skip-string-normalization = true
extend-exclude = "docs"

[tool.isort]
profile = "black"

[tool.ruff]
line-length = 120
select = ["E", "F", "UP"]
ignore = ["UP015"]
unfixable = ["F401"]
target-version = "py37"
