name: Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - 'tox.ini'
      - '**.py'
      - '.github/workflows/python-test.yml'

  pull_request:
    branches: [ "master" ]
    paths:
      - 'tox.ini'
      - '**.py'
      - '.github/workflows/python-test.yml'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
        speed: ["slow"]
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install tox
        
    - name: Test with tox
      env:
        TOXENV: ${{ matrix.speed }}
      run: tox

    - name: Upload coverage data to coveralls.io
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        coveralls --service=github
